name: surf_practice_magic_ball
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: 3.0.3 # Dart SDK version
  flutter: 3.10.3 # Flutter SDK version

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  http: ^1.0.0
  flutter_riverpod: ^2.3.6
  dio: ^5.3.0
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1
  json_annotation: ^4.8.1
  shake: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - docs/assets/ball.png
    - docs/assets/ellipse_base.png
    - docs/assets/ellipse_blue.png
    - docs/assets/star.png
    - docs/assets/small_star.png
